# Generated by Django 3.2.6 on 2021-08-10 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transgg', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
