# Generated by Django 3.2.6 on 2021-08-10 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transgg', '0002_alter_category_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=56)),
                ('url', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=48)),
                ('body', models.TextField()),
                ('visible', models.BooleanField(default=True)),
                ('icon', models.CharField(blank=True, max_length=24)),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name='category',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='question',
            name='long_answer',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='question',
            name='source',
            field=models.TextField(blank=True),
        ),
    ]
